### ISSUE TITLE
Flatten arrays in php could also have array_column

### ISSUE THREAD

**Issue by strayobject** [mark-gerarts/lambda-out-loud#1]
Hi,

It's a somewhat specific use case, i.e. use one column for key and one for value, but since it is the easiest way to achieve this type of flattening I thought it might be worthwhile to add to your post. Here is an example https://3v4l.org/MkKnD

What do you think?

**Comment by mark-gerarts** [comment]
Absolutely, it's such a useful function. I've updated the post, thank you for the suggestion!

**Comment by strayobject** [comment]
That's cool, I did not know about the `null` option to reindex the array. :) Thanks!
